interfaces:
- description: Uplink | AGG3 E1/1 | Area3 | 10.1.3.4/30
  name: Ethernet0/0
- description: Uplink | AGG4 E0/3 | Area3 | 10.1.3.12/30
  name: Ethernet0/1
- description: Site-C2 | Router-ID 10.0.0.32
  name: Loopback0
