all:
  vars:
    ansible_user: admin
    ansible_password: cisco123
    ansible_enable_password: cisco123
    ansible_connection: network_cli
    ansible_network_os: cisco.ios.ios
    ansible_host: 192.168.1.249
    ansible_become: true
    ansible_become_method: enable
    ansible_command_timeout: 60

  children:
    core:
      hosts:
        AGG1:
          ansible_port: 32769
        AGG2:
          ansible_port: 32770
        AGG3:
          ansible_port: 32771
        AGG4:
          ansible_port: 32772

    edge_a:
      hosts:
        Site-A1:
          ansible_port: 32773
        Site-A2:
          ansible_port: 32774

    edge_b:
      hosts:
        Site-B1:
          ansible_port: 32775
        Site-B2:
          ansible_port: 32776

    edge_c:
      hosts:
        Site-C1:
          ansible_port: 32778
        Site-C2:
          ansible_port: 32777

    edge_d:
      hosts:
        Site-D1:
          ansible_port: 32780
        Site-D2:
          ansible_port: 32779
